<?php

namespace Database\Seeders;

use App\Models\Dosen;
use Illuminate\Database\Seeder;

class DosenTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dosen = array(
            array(
            'user_id' => '3',
            'nidn' => '0000000002',
            'name' => 'Dino Haratma',
            'gelar' => 'P. M.Kom',
            'tgl_lahir' => '1990-01-22',
            'email' => 'assd@asd.com',
            'telp' => '081080808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000003',
            'name' => 'Andi Eka S',
            'gelar' => 'Dr.',
            'tgl_lahir' => '1990-01-22',
            'email' => 'aasd@asd.com',
            'telp' => '080820808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000004',
            'name' => 'Dr. Oo Abdul Rasyid',
            'gelar' => '',
            'tgl_lahir' => '1990-01-22',
            'email' => 'as3d@asd.com',
            'telp' => '083080808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000005',
            'name' => 'Dr. Noor Rachmad',
            'gelar' => 'MA',
            'tgl_lahir' => '1990-01-22',
            'email' => 'a1sd@asd.com',
            'telp' => '0801180808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000006',
            'name' => 'Dr. RA. Hangesti Emi Wodyasari',
            'gelar' => '',
            'tgl_lahir' => '1990-01-22',
            'email' => 'as2d@asd.com',
            'telp' => '080280808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000007',
            'name' => 'Dra. Endang RD',
            'gelar' => 'M. Kom',
            'tgl_lahir' => '1990-01-22',
            'email' => 'as4d@asd.com',
            'telp' => '084080808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000008',
            'name' => 'Dra. Indrati Sukmadi',
            'gelar' => 'MSc',
            'tgl_lahir' => '1990-01-22',
            'email' => 'as5d@asd.com',
            'telp' => '080580808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000009',
            'name' => 'Dra. Sulistyowati',
            'gelar' => 'M. Kom',
            'tgl_lahir' => '1990-01-22',
            'email' => 'a6sd@asd.com',
            'telp' => '080680808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000010',
            'name' => 'Drs. Abdul Gaffar',
            'gelar' => 'M.Hum',
            'tgl_lahir' => '1990-01-22',
            'email' => 'a7sd@asd.com',
            'telp' => '080780808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000011',
            'name' => 'Drs. Budi Prasetyo',
            'gelar' => 'MT',
            'tgl_lahir' => '1990-01-22',
            'email' => 'a8sd@asd.com',
            'telp' => '088080808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000012',
            'name' => 'Drs. Dickson',
            'gelar' => '',
            'tgl_lahir' => '1990-01-22',
            'email' => 'as9d@asd.com',
            'telp' => '080980808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000013',
            'name' => 'Drs. Yuniwardhana',
            'gelar' => 'Msi',
            'tgl_lahir' => '1990-01-22',
            'email' => 'as0d@asd.com',
            'telp' => '080800808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000014',
            'name' => 'Harini K',
            'gelar' => 'MS. Eng',
            'tgl_lahir' => '1990-01-22',
            'email' => 'as11d@asd.com',
            'telp' => '0811080808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000015',
            'name' => 'Husni',
            'gelar' => 'M. Kom, MSc',
            'tgl_lahir' => '1990-01-22',
            'email' => 'as12d@asd.com',
            'telp' => '0808120808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000016',
            'name' => 'Ir. Sumiarti',
            'gelar' => 'M.Kom',
            'tgl_lahir' => '1990-01-22',
            'email' => 'as13d@asd.com',
            'telp' => '0813080808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000017',
            'name' => 'M. Ramli',
            'gelar' => 'ST',
            'tgl_lahir' => '1990-01-22',
            'email' => 'as14d@asd.com',
            'telp' => '0814080808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000018',
            'name' => 'Melani Indriasari',
            'gelar' => 'M.Kom',
            'tgl_lahir' => '1990-01-22',
            'email' => 'as15d@asd.com',
            'telp' => '0801580808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000019',
            'name' => 'Moh Soleh',
            'gelar' => 'M.Kom',
            'tgl_lahir' => '1990-01-22',
            'email' => 'a16sd@asd.com',
            'telp' => '0801680808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000020',
            'name' => 'Ramses Simbolon',
            'gelar' => 'STh',
            'tgl_lahir' => '1990-01-22',
            'email' => '17asd@asd.com',
            'telp' => '0817080808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000021',
            'name' => 'Romo Antonius',
            'gelar' => '',
            'tgl_lahir' => '1990-01-22',
            'email' => 'a18sd@asd.com',
            'telp' => '0818080808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000022',
            'name' => 'Siti Nadroh',
            'gelar' => ' S.Ag, MA',
            'tgl_lahir' => '1990-01-22',
            'email' => 'a19sd@asd.com',
            'telp' => '0801980808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000023',
            'name' => 'Sunarto',
            'gelar' => 'ST, M. Kom',
            'tgl_lahir' => '1990-01-22',
            'email' => 'a22sd@asd.com',
            'telp' => '0822080808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000024',
            'name' => 'Suryo Bramasto',
            'gelar' => 'MT',
            'tgl_lahir' => '1990-01-22',
            'email' => 'a21sd@asd.com',
            'telp' => '0821080808',
            'alamat' => 'jalan sesame.St',
            ),
            array(
            'user_id' => '5',
            'nidn' => '0000000025',
            'name' => 'Yustina Sri Suharini',
            'gelar' => 'MT',
            'tgl_lahir' => '1990-01-22',
            'email' => 'a20sd@asd.com',
            'telp' => '0208080808',
            'alamat' => 'jalan sesame.St',
            ),
        );

        
        foreach ($dosen as $item)
        {
            Dosen::create([
                'user_id' => $item['user_id'],
                'nidn' => $item['nidn'],
                'name' => $item['name'],
                'gelar' => $item['gelar'],
                'tgl_lahir' => $item['tgl_lahir'],
                'email' => $item['email'],
                'telp' => $item['telp'],
                'alamat' => $item['alamat'],
            ]);
        }


    }
}
